import xlwt
import random
from datetime import datetime

style1 = xlwt.easyxf('font: name Arial, color-index blue, italic on', num_format_str='#,##0')
style2 = xlwt.easyxf(num_format_str='YYYY-MM-DD-HH-MM-SS')

wb = xlwt.Workbook()
ws = wb.add_sheet('Generated by Python')


for row in range(0,10000):

	ws.write(row,0,datetime.now(),style2)
	for column in range(1,11):
		ws.write(row, column, xlwt.Formula('randbetween(1000,100000)'))


i = 1
while i <= 20: 
	wb.add_sheet('Generated by Python - ' + str(i))
	i = i + 1



wb.save('007_'+str(random.randint(10000,99999))+'.xls')
